# Configuration based on https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 30

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 30

  - package-ecosystem: "docker"
    directory: "/docker/sql"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 30

  - package-ecosystem: "docker"
    directory: "/src/Microsoft.Health.Dicom.Functions.App/Docker"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 30

  - package-ecosystem: "docker"
    directory: "/src/Microsoft.Health.Dicom.Web"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 30

  - package-ecosystem: "docker"
    directory: "/converter/dicom-cast/src/Microsoft.Health.DicomCast.Hosting"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 30

  - package-ecosystem: "docker"
    directory: "/tools/uploader-function/src/DicomUploaderFunction"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 30

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 30

  - package-ecosystem: "npm"
    directory: "/tools/dicom-web-electron"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 30

  - package-ecosystem: "nuget"
    directory: "/converter/dicom-cast"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 30

  - package-ecosystem: "nuget"
    directory: "/tools/dicom-auth-test/Microsoft.Health.Web.Dicom.Tool"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 30

  - package-ecosystem: "nuget"
    directory: "/tools/uploader-function"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 30
